README.md

Added link and copied blurb from official documentation to provide context, especially for folks who do not know what a syntax macro is.

Added link to official docs site

---

README.md
newgr.js

Added common pattern for creating a new GlideRecord and removed duplicate information from the readme file.

Added newgr and updated readme

---

spModal/Large Popup HTML Message.js

Present a modal popup in Service Portal and a standard g_form prompt in native UI

Create Large Popup HTML Message.js

---

eslint/README.md
eslint/eslint
eslint/eslintDisableBlock
eslint/eslintDisableLine
eslint/eslintDisableNext
eslint/eslintEnableBlock

Adds editor macros for inline eslint configuration as described in eslint/README.md

Inline eslint configuration macros

---

General/for.js
General/foreach.js
General/if.js
General/while.js

Uploading some basic Syntax Editor Macros to improve code speed with simple things like IF statements & Loops

Syntax Editor Macros for IF Statement & Common Loops

---

General/ArrayFilter.js
General/map.js
GlideRecord/applyEncodedQuery.js

applyEncodedQuery(String queryString) method - Sets the values of the specified encoded query terms and applies them to the current GlideRecord

Syntax macros

---

Client Scripts/Mandatory Fields onSubmit.js

Cancelled the other pull request as i got muddle up with how to make the changes so started fresh

Create Mandatory Fields onSubmit.js

---

GlideSystem/To find Specific String using Index of.js

To find any string in the Variable
var value = current.variables.variablename.getDisplayValue();
if(value.indexOf('string') > -1){	
//to find a particular string example: Production
current.fieldname = value;
//if the value is found then set the value
}

Create To find Specific String using Index of.js

---

IP Address/README.md
IP Address/isIpv4.js
IP Address/isIpv6.js
IP Address/isValidIp.js

Various implementations of IPAddress API.

Various implementations of IPAddress API

---

GlideSecureRandomUtil/GlideSecureRandomUtil.js

Implementation of GlideSecureRandomUtil API

GlideSecureRandomUtil API

---

Client-Server Request-Response in Widget/client-request.js
Client-Server Request-Response in Widget/server-template.js

Syntax for request and response between the client-server script in widget. Also, basic template syntax for server scrip, useful for initiating with basic template while starting work on server script in a widget.

Request & Response between Client & Server Script in Widget

---

Sub Flow/SubFlowClient.js
Sub Flow/readme.md

This repository contains a client script module for ServiceNow that initiates and manages the execution of a subflow.

Subflow client

---

Flow Designer/Extract Data From Excel/code.js
Flow Designer/Extract Data From Excel/readme.md

This macro will be helpful in extracting data from the attachment and passing the Excel data as input in Flow Designer Action.
E.g
100 CIs are loaded via Excel template and you need to extract the data from Excel once the request is submitted and query the CMDB say BMC via integration to look for all the attributes.

Bird 03macrosoct2023

---

Script Include/To Inherit a Script Include/inheritScriptInclude.js

Created a syntax macro which we can use while inheriting a script include from the parent script include.

Created a syntax macro to inherit a script include.

---

APIs/CartAPI/CartJS api.js

and a try function is used to see if any error
occur

duplicates have been resolved

---

GlideRecord/gr-update-or-insert.js

This checks if a record exists based on a specific query. If it does, it updates the designated field; if not, it creates a new record.

GlideRecord (Update Or Insert)

---

Error Handling/Error Handling.js
Error Handling/README.md

This includes a simple error handling example using syntax macros to streamline the process. The following code snippet captures any runtime errors encountered during client script execution and uses `g_form.addErrorMessage` to notify the user, improving the user experience by providing clear feedback.

Error Handling with Syntax Macros

---

JSON/JSON_Response_Builder.js

<h1>buildJsonResponse Utility Function</h1>
<p>
This utility function helps in constructing standardized JSON responses for any operation. It accepts three parameters:
</p>
<ul>
<li><strong>success</strong> (Boolean): Indicates whether the operation was successful or not.</li>
<li><strong>message</strong> (String): Provides a message related to the operation's outcome.</li>
<li><strong>data</strong> (Object): Contains additional data relevant to the operation, such as key-value pairs or complex objects.</li>
</ul>
<h2>Function Overview</h2>
<pre><code>
function buildJsonResponse(success, message, data) {
return JSON.stringify({
success: success,
message: message,
data: data
});
}
</code></pre>
<h3>Parameters:</h3>
<ul>
<li><strong>success</strong> (Boolean): <code>true</code> or …

JSON_Response_Builder.js

---

Validation Messages/README.md
Validation Messages/returnChecks.js

To generate informed messages of error with reference to sys_properties values configured in the platform.

Qi Xing Validation Messages

---

GlideExcelParser/readExcelFile.js
GlideSysAttachment/getAttachments.js

Syntax Macro for ExcelParser API to parse an Excel Attachment

Glide_excel_parser

---

Scheduled Jobs/User Deactivation Macro/ReadMe.md
Scheduled Jobs/User Deactivation Macro/User Deactivate Job.js

This macro automatically deactivates users who haven’t logged in for a specified number of days(90).

Scheduled job macro

---

General/arraySortEs5.js
General/arraySortEs6.js

I have created two editor macros, one supports the ES5 syntax, the other supports the ES6+. The purpose of these macros are the same, helps to implement array sorting logic.

New editor macro: array sorting function

---

GlideModal/g_model for workspace client script

g_model.showframe() for workspace client script to open models

g_model for workspace client script
